---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      kind: Gateway
  hostnames:
    - jellyfin.ko1c5cb5wm.anyoqr1.shoot.emk.fuga.cloud
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096